//
// AlbumApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlbumApiModel: Codable {
    public enum ModelType: String, Codable, CaseIterable {
        case classic
        case new
    }

    public var type: ModelType
    public var spotifyId: String?
    public var name: String
    public var artist: String
    public var score: Float?
    public var images: [ImageApiModel]?

    public init(type: ModelType, spotifyId: String?, name: String, artist: String, score: Float?, images: [ImageApiModel]?) {
        self.type = type
        self.spotifyId = spotifyId
        self.name = name
        self.artist = artist
        self.score = score
        self.images = images
    }
}
