//
// EventApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EventApiModel: Codable {
    public var number: Int
    public var date: String?
    public var location: LocationApiModel?
    public var classicAlbum: AlbumApiModel?
    public var newAlbum: AlbumApiModel?
    public var playlist: PlaylistApiModel?

    public init(number: Int, date: String?, location: LocationApiModel?, classicAlbum: AlbumApiModel?, newAlbum: AlbumApiModel?, playlist: PlaylistApiModel?) {
        self.number = number
        self.date = date
        self.location = location
        self.classicAlbum = classicAlbum
        self.newAlbum = newAlbum
        self.playlist = playlist
    }
}
