//
// ImageApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ImageApiModel: Codable {

    public var size: Int
    public var url: String

    public init(size: Int, url: String) {
        self.size = size
        self.url = url
    }


}

