//
// LocationApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LocationApiModel: Codable {
    public var name: String
    public var latitude: Double
    public var longitude: Double

    public init(name: String, latitude: Double, longitude: Double) {
        self.name = name
        self.latitude = latitude
        self.longitude = longitude
    }
}
