//
// PlaylistApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PlaylistApiModel: Codable { 


    public var spotifyId: String
    public var name: String
    public var owner: String
    public var images: [ImageApiModel]?

    public init(spotifyId: String, name: String, owner: String, images: [ImageApiModel]?) {
        self.spotifyId = spotifyId
        self.name = name
        self.owner = owner
        self.images = images
    }

}
